"""Initial migrations for Phase 0

Revision ID: f5fc729c0b2d
Revises: 
Create Date: 2026-03-21 21:12:52.055051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f5fc729c0b2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentinel_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('shadow_mode', sa.Boolean(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('total_blocked', sa.Integer(), nullable=False),
    sa.Column('total_escalated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('sentinel_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('proposed_args', sqlite.JSON(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('blocking_reason', sa.Text(), nullable=True),
    sa.Column('retry_feedback', sa.Text(), nullable=True),
    sa.Column('policy_triggered', sa.String(), nullable=True),
    sa.Column('evidence_used', sqlite.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sentinel_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentinel_validations')
    op.drop_table('sentinel_runs')
    # ### end Alembic commands ###
